package com.yral.shared.analytics.constants

/**
 * All analytic event names used across the app.
 */
enum class FeatureEvents {
    FIRST_APP_LAUNCH,
    SPLASH_SCREEN_VIEWED,
    APP_ONBOARDING_SHOWN,

    // Auth / Signup / Login
    AUTH_SCREEN_VIEWED,
    SIGNUP_CLICKED,
    SIGNUP_JOURNEY_SELECTED,
    SIGNUP_INITIATED,
    SIGNUP_SUCCESS,
    LOGIN_SUCCESS,
    AUTH_FAILED,

    // Home
    HOME_PAGE_VIEWED,
    BOTTOM_NAVIGATION_CLICKED,

    // Video / Feed
    VIDEO_IMPRESSION,
    VIDEO_STARTED,
    VIDEO_VIEWED,
    VIDEO_CLICKED,
    NSFW_ENABLED,
    VIDEO_REPORTED,
    DELETE_VIDEO_INITIATED,
    VIDEO_DELETED,
    VIDEO_DURATION_WATCHED,
    ENABLE_PUSH_NOTIFICATION_POPUP_SHOWN,
    NOTIFICATIONS_ENABLED,
    FEED_TOGGLE_CLICKED,
    VIDEO_DOWNLOADED,

    // Game
    GAME_VOTED,
    GAME_PLAYED,
    GAME_TUTORIAL_SHOWN,
    GAME_CONCLUDED_BOTTOMSHEET_CLICKED,
    FORCED_GAMEPLAY_NUDGE_SHOWN,

    // Menu
    MENU_PAGE_VIEWED,
    MENU_CLICKED,

    // Upload
    UPLOAD_VIDEO_PAGE_VIEWED,
    VIDEO_CREATION_PAGE_VIEWED,
    SELECT_FILE_CLICKED,
    FILE_SELECTION_SUCCESS,
    VIDEO_UPLOAD_INITIATED,
    VIDEO_UPLOAD_SUCCESS,
    VIDEO_UPLOAD_ERROR_SHOWN,
    VIDEO_UPLOAD_TYPE_SELECTED,
    VIDEO_GENERATION_MODEL_SELECTED,
    CREATE_AI_VIDEO_CLICKED,
    AI_VIDEO_GENERATED,

    // Profile
    PROFILE_PAGE_VIEWED,
    UPLOAD_VIDEO_CLICKED,
    EDIT_PROFILE_STARTED,
    EDIT_PROFILE_COMPLETED,
    EDIT_PROFILE_CANCELLED,

    // Wallet
    WALLET_PAGE_VIEWED,
    CENTS_TO_DOLR_CONVERTED,
    THIRD_PARTY_WALLET_TRANSFERRED,
    SATS_TO_BTC_CONVERTED,
    VIDEO_VIEWS_REWARDS_NUDGE_SHOWN,
    HOW_TO_EARN_CLICKED,

    // Referral
    REFERRAL_RECEIVED,
    REFER_AND_EARN_PAGE_VIEWED,
    REFERRAL_HISTORY_VIEWED,
    SHARE_INVITES_CLICKED,

    // Leaderboard
    LEADERBOARD_PAGE_VIEWED,
    LEADERBOARD_PAGE_LOADED,
    LEADERBOARD_TAB_CLICKED,
    LEADERBOARD_CALENDAR_CLICKED,
    LEADERBOARD_DAY_SELECTED,

    // Recharge
    AIRDROP_CLAIMED,

    // Share
    VIDEO_SHARE_CLICKED,
    SHARE_APP_OPENED_FROM_LINK,

    // Follow
    USER_FOLLOWED,
    USER_UNFOLLOWED,
    FOLLOWERS_LIST_VIEWED,

    ;

    fun getEventName(): String =
        when (this) {
            VIDEO_DURATION_WATCHED -> "VideoDurationWatched"
            else -> name.lowercase()
        }
}
