repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.1
    hooks:
      - id: swiftlint
        entry: swiftlint --strict

  - repo: local
    hooks:
      - id: ktlint
        name: ktlint
        entry: ktlint
        language: system
        types: [kotlin]
        pass_filenames: true

      - id: detekt
        name: detekt
        entry: detekt
        language: system
        types: [kotlin]
        pass_filenames: true
        excludes: '**/build.gradle.kts,**/settings.gradle.kts'
