repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.1
    hooks:
      - id: swiftlint
        entry: swiftlint --strict

  - repo: local
    hooks:
      - id: ktlint
        name: ktlint
        entry: ktlint
        language: system
        pass_filenames: true
        files: \.kt$

      - id: detekt
        name: detekt
        entry: ./gradlew detekt
        language: system
        pass_filenames: false
        files: \.kt$
