package com.yral.shared.features.auth.data.models

/**
 * IC delegation payload — used by createAiAccount.
 *
 * Historically these types were generated by UniFFI from the Rust FFI layer.
 * They are kept here as plain Kotlin data classes so the auth API contract
 * remains stable while the IC identity layer is being removed.
 *
 * Note: Remove entirely once createAiAccount is migrated to JWT-only auth.
 */
data class DelegationPayload(
    val pubkey: ByteArray,
    val expiration: Long,
    val targets: List<String>?,
)

data class SignedDelegationPayload(
    val delegation: DelegationPayload,
    val signature: ByteArray,
)
