name: 'Send Release Notification'
description: 'Sends a notification to Google Chat about new releases'

inputs:
  webhook_url:
    description: 'Google Chat webhook URL'
    required: true
  release_tag:
    description: 'Release tag'
    required: true
  release_name:
    description: 'Release name'
    required: true
  release_url:
    description: 'Release URL'
    required: true
  release_body:
    description: 'Release body'
    required: true
  published_at:
    description: 'Published at'
    required: true
  author:
    description: 'Author'
    required: true
  workflow_url:
    description: 'Workflow run URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send release notification
      shell: bash
      run: |
        # Process and escape release notes for JSON
        RELEASE_NOTES=$(echo "${{ inputs.release_body }}" | .github/helperscripts/cleanup_release_notes_for_google_chat.sh | jq -Rs .)
        
        curl -X POST "${{ inputs.webhook_url }}" \
        -H "Content-Type: application/json" \
        -d '{
          "cardsV2": [
            {
              "cardId": "release-alert",
              "card": {
                "header": {
                  "title": "New Release Alert!",
                  "subtitle": "Hot-or-Not Backend Canister",
                  "imageUrl": "https://avatars.githubusercontent.com/u/79742232?s=200&v=4"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "decoratedText": {
                          "startIcon": { "knownIcon": "DESCRIPTION" },
                          "topLabel": "Release",
                          "text": "${{ inputs.release_name }} ( ${{ inputs.release_tag }} )"
                        }
                      },
                      {
                        "decoratedText": {
                          "startIcon": { "knownIcon": "PERSON" },
                          "topLabel": "Author",
                          "text": "${{ inputs.author }}"
                        }
                      },
                      {
                        "decoratedText": {
                          "startIcon": { "knownIcon": "INVITE" },
                          "topLabel": "Published",
                          "text": "${{ inputs.published_at }}"
                        }
                      }
                    ]
                  },
                  {
                    "header": "Release Notes",
                    "widgets": [
                      { "textParagraph": { "text": '"$RELEASE_NOTES"' } }
                    ]
                  },
                  {
                    "widgets": [
                      {
                        "buttonList": {
                          "buttons": [
                            {
                              "text": "View Release",
                              "onClick": {
                                "openLink": {
                                  "url": "${{ inputs.release_url }}"
                                }
                              }
                            }
                          ]
                        }
                      }
                    ]
                  },
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "<i><a href=\"${{ inputs.workflow_url }}\">View workflow run</a></i>"
                        }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }' 