package com.yral.shared.libs.phonevalidation.countries

object CountriesDataSource {
    @Suppress("LongMethod", "MaxLineLength")
    fun getAllCountries(): List<Country> =
        listOf(
            Country("AF", "Afghanistan", "+93", Country.getFlagUrl("AF")),
            Country("AL", "Albania", "+355", Country.getFlagUrl("AL")),
            Country("DZ", "Algeria", "+213", Country.getFlagUrl("DZ")),
            Country("AD", "Andorra", "+376", Country.getFlagUrl("AD")),
            Country("AO", "Angola", "+244", Country.getFlagUrl("AO")),
            Country("AG", "Antigua and Barbuda", "+1-268", Country.getFlagUrl("AG"), minLength = 10, maxLength = 10),
            Country("AR", "Argentina", "+54", Country.getFlagUrl("AR"), minLength = 10, maxLength = 10),
            Country("AM", "Armenia", "+374", Country.getFlagUrl("AM")),
            Country("AU", "Australia", "+61", Country.getFlagUrl("AU"), minLength = 9, maxLength = 9),
            Country("AT", "Austria", "+43", Country.getFlagUrl("AT"), minLength = 10, maxLength = 13),
            Country("AZ", "Azerbaijan", "+994", Country.getFlagUrl("AZ"), minLength = 9, maxLength = 9),
            Country("BS", "Bahamas", "+1-242", Country.getFlagUrl("BS"), minLength = 10, maxLength = 10),
            Country("BH", "Bahrain", "+973", Country.getFlagUrl("BH"), minLength = 8, maxLength = 8),
            Country("BD", "Bangladesh", "+880", Country.getFlagUrl("BD"), minLength = 10, maxLength = 10),
            Country("BB", "Barbados", "+1-246", Country.getFlagUrl("BB"), minLength = 10, maxLength = 10),
            Country("BY", "Belarus", "+375", Country.getFlagUrl("BY")),
            Country("BE", "Belgium", "+32", Country.getFlagUrl("BE")),
            Country("BZ", "Belize", "+501", Country.getFlagUrl("BZ")),
            Country("BJ", "Benin", "+229", Country.getFlagUrl("BJ")),
            Country("BT", "Bhutan", "+975", Country.getFlagUrl("BT")),
            Country("BO", "Bolivia", "+591", Country.getFlagUrl("BO")),
            Country("BA", "Bosnia and Herzegovina", "+387", Country.getFlagUrl("BA")),
            Country("BW", "Botswana", "+267", Country.getFlagUrl("BW")),
            Country("BR", "Brazil", "+55", Country.getFlagUrl("BR")),
            Country("BN", "Brunei", "+673", Country.getFlagUrl("BN")),
            Country("BG", "Bulgaria", "+359", Country.getFlagUrl("BG")),
            Country("BF", "Burkina Faso", "+226", Country.getFlagUrl("BF")),
            Country("BI", "Burundi", "+257", Country.getFlagUrl("BI")),
            Country("KH", "Cambodia", "+855", Country.getFlagUrl("KH")),
            Country("CM", "Cameroon", "+237", Country.getFlagUrl("CM")),
            Country("CA", "Canada", "+1", Country.getFlagUrl("CA"), minLength = 10, maxLength = 10),
            Country("CV", "Cape Verde", "+238", Country.getFlagUrl("CV")),
            Country("CF", "Central African Republic", "+236", Country.getFlagUrl("CF")),
            Country("TD", "Chad", "+235", Country.getFlagUrl("TD")),
            Country("CL", "Chile", "+56", Country.getFlagUrl("CL")),
            Country("CN", "China", "+86", Country.getFlagUrl("CN"), minLength = 11, maxLength = 11),
            Country("CO", "Colombia", "+57", Country.getFlagUrl("CO")),
            Country("KM", "Comoros", "+269", Country.getFlagUrl("KM")),
            Country("CG", "Congo", "+242", Country.getFlagUrl("CG")),
            Country("CD", "Congo (Democratic Republic)", "+243", Country.getFlagUrl("CD")),
            Country("CR", "Costa Rica", "+506", Country.getFlagUrl("CR")),
            Country("HR", "Croatia", "+385", Country.getFlagUrl("HR")),
            Country("CU", "Cuba", "+53", Country.getFlagUrl("CU")),
            Country("CY", "Cyprus", "+357", Country.getFlagUrl("CY")),
            Country("CZ", "Czech Republic", "+420", Country.getFlagUrl("CZ")),
            Country("DK", "Denmark", "+45", Country.getFlagUrl("DK")),
            Country("DJ", "Djibouti", "+253", Country.getFlagUrl("DJ")),
            Country("DM", "Dominica", "+1-767", Country.getFlagUrl("DM"), minLength = 10, maxLength = 10),
            Country("DO", "Dominican Republic", "+1-809", Country.getFlagUrl("DO"), minLength = 10, maxLength = 10),
            Country("EC", "Ecuador", "+593", Country.getFlagUrl("EC")),
            Country("EG", "Egypt", "+20", Country.getFlagUrl("EG")),
            Country("SV", "El Salvador", "+503", Country.getFlagUrl("SV")),
            Country("GQ", "Equatorial Guinea", "+240", Country.getFlagUrl("GQ")),
            Country("ER", "Eritrea", "+291", Country.getFlagUrl("ER")),
            Country("EE", "Estonia", "+372", Country.getFlagUrl("EE")),
            Country("ET", "Ethiopia", "+251", Country.getFlagUrl("ET")),
            Country("FJ", "Fiji", "+679", Country.getFlagUrl("FJ")),
            Country("FI", "Finland", "+358", Country.getFlagUrl("FI")),
            Country("FR", "France", "+33", Country.getFlagUrl("FR")),
            Country("GA", "Gabon", "+241", Country.getFlagUrl("GA")),
            Country("GM", "Gambia", "+220", Country.getFlagUrl("GM")),
            Country("GE", "Georgia", "+995", Country.getFlagUrl("GE")),
            Country("DE", "Germany", "+49", Country.getFlagUrl("DE")),
            Country("GH", "Ghana", "+233", Country.getFlagUrl("GH")),
            Country("GR", "Greece", "+30", Country.getFlagUrl("GR")),
            Country("GD", "Grenada", "+1-473", Country.getFlagUrl("GD"), minLength = 10, maxLength = 10),
            Country("GT", "Guatemala", "+502", Country.getFlagUrl("GT")),
            Country("GN", "Guinea", "+224", Country.getFlagUrl("GN")),
            Country("GW", "Guinea-Bissau", "+245", Country.getFlagUrl("GW")),
            Country("GY", "Guyana", "+592", Country.getFlagUrl("GY")),
            Country("HT", "Haiti", "+509", Country.getFlagUrl("HT")),
            Country("HN", "Honduras", "+504", Country.getFlagUrl("HN")),
            Country("HU", "Hungary", "+36", Country.getFlagUrl("HU")),
            Country("IS", "Iceland", "+354", Country.getFlagUrl("IS")),
            Country("IN", "India", "+91", Country.getFlagUrl("IN"), minLength = 10, maxLength = 10),
            Country("ID", "Indonesia", "+62", Country.getFlagUrl("ID")),
            Country("IR", "Iran", "+98", Country.getFlagUrl("IR")),
            Country("IQ", "Iraq", "+964", Country.getFlagUrl("IQ")),
            Country("IE", "Ireland", "+353", Country.getFlagUrl("IE")),
            Country("IL", "Israel", "+972", Country.getFlagUrl("IL")),
            Country("IT", "Italy", "+39", Country.getFlagUrl("IT")),
            Country("CI", "Ivory Coast", "+225", Country.getFlagUrl("CI")),
            Country("JM", "Jamaica", "+1-876", Country.getFlagUrl("JM"), minLength = 10, maxLength = 10),
            Country("JP", "Japan", "+81", Country.getFlagUrl("JP")),
            Country("JO", "Jordan", "+962", Country.getFlagUrl("JO")),
            Country("KZ", "Kazakhstan", "+7", Country.getFlagUrl("KZ")),
            Country("KE", "Kenya", "+254", Country.getFlagUrl("KE")),
            Country("KI", "Kiribati", "+686", Country.getFlagUrl("KI")),
            Country("KW", "Kuwait", "+965", Country.getFlagUrl("KW")),
            Country("KG", "Kyrgyzstan", "+996", Country.getFlagUrl("KG")),
            Country("LA", "Laos", "+856", Country.getFlagUrl("LA")),
            Country("LV", "Latvia", "+371", Country.getFlagUrl("LV")),
            Country("LB", "Lebanon", "+961", Country.getFlagUrl("LB")),
            Country("LS", "Lesotho", "+266", Country.getFlagUrl("LS")),
            Country("LR", "Liberia", "+231", Country.getFlagUrl("LR")),
            Country("LY", "Libya", "+218", Country.getFlagUrl("LY")),
            Country("LI", "Liechtenstein", "+423", Country.getFlagUrl("LI")),
            Country("LT", "Lithuania", "+370", Country.getFlagUrl("LT")),
            Country("LU", "Luxembourg", "+352", Country.getFlagUrl("LU")),
            Country("MG", "Madagascar", "+261", Country.getFlagUrl("MG")),
            Country("MW", "Malawi", "+265", Country.getFlagUrl("MW")),
            Country("MY", "Malaysia", "+60", Country.getFlagUrl("MY")),
            Country("MV", "Maldives", "+960", Country.getFlagUrl("MV")),
            Country("ML", "Mali", "+223", Country.getFlagUrl("ML")),
            Country("MT", "Malta", "+356", Country.getFlagUrl("MT")),
            Country("MH", "Marshall Islands", "+692", Country.getFlagUrl("MH")),
            Country("MR", "Mauritania", "+222", Country.getFlagUrl("MR")),
            Country("MU", "Mauritius", "+230", Country.getFlagUrl("MU")),
            Country("MX", "Mexico", "+52", Country.getFlagUrl("MX")),
            Country("FM", "Micronesia", "+691", Country.getFlagUrl("FM")),
            Country("MD", "Moldova", "+373", Country.getFlagUrl("MD")),
            Country("MC", "Monaco", "+377", Country.getFlagUrl("MC")),
            Country("MN", "Mongolia", "+976", Country.getFlagUrl("MN")),
            Country("ME", "Montenegro", "+382", Country.getFlagUrl("ME")),
            Country("MA", "Morocco", "+212", Country.getFlagUrl("MA")),
            Country("MZ", "Mozambique", "+258", Country.getFlagUrl("MZ")),
            Country("MM", "Myanmar", "+95", Country.getFlagUrl("MM")),
            Country("NA", "Namibia", "+264", Country.getFlagUrl("NA")),
            Country("NR", "Nauru", "+674", Country.getFlagUrl("NR")),
            Country("NP", "Nepal", "+977", Country.getFlagUrl("NP")),
            Country("NL", "Netherlands", "+31", Country.getFlagUrl("NL")),
            Country("NZ", "New Zealand", "+64", Country.getFlagUrl("NZ")),
            Country("NI", "Nicaragua", "+505", Country.getFlagUrl("NI")),
            Country("NE", "Niger", "+227", Country.getFlagUrl("NE")),
            Country("NG", "Nigeria", "+234", Country.getFlagUrl("NG")),
            Country("KP", "North Korea", "+850", Country.getFlagUrl("KP")),
            Country("MK", "North Macedonia", "+389", Country.getFlagUrl("MK")),
            Country("NO", "Norway", "+47", Country.getFlagUrl("NO")),
            Country("OM", "Oman", "+968", Country.getFlagUrl("OM")),
            Country("PK", "Pakistan", "+92", Country.getFlagUrl("PK")),
            Country("PW", "Palau", "+680", Country.getFlagUrl("PW")),
            Country("PS", "Palestine", "+970", Country.getFlagUrl("PS")),
            Country("PA", "Panama", "+507", Country.getFlagUrl("PA")),
            Country("PG", "Papua New Guinea", "+675", Country.getFlagUrl("PG")),
            Country("PY", "Paraguay", "+595", Country.getFlagUrl("PY")),
            Country("PE", "Peru", "+51", Country.getFlagUrl("PE")),
            Country("PH", "Philippines", "+63", Country.getFlagUrl("PH")),
            Country("PL", "Poland", "+48", Country.getFlagUrl("PL")),
            Country("PT", "Portugal", "+351", Country.getFlagUrl("PT")),
            Country("QA", "Qatar", "+974", Country.getFlagUrl("QA")),
            Country("RO", "Romania", "+40", Country.getFlagUrl("RO")),
            Country("RU", "Russia", "+7", Country.getFlagUrl("RU")),
            Country("RW", "Rwanda", "+250", Country.getFlagUrl("RW")),
            Country("KN", "Saint Kitts and Nevis", "+1-869", Country.getFlagUrl("KN"), minLength = 10, maxLength = 10),
            Country("LC", "Saint Lucia", "+1-758", Country.getFlagUrl("LC"), minLength = 10, maxLength = 10),
            Country("VC", "Saint Vincent and the Grenadines", "+1-784", Country.getFlagUrl("VC"), minLength = 10, maxLength = 10),
            Country("WS", "Samoa", "+685", Country.getFlagUrl("WS")),
            Country("SM", "San Marino", "+378", Country.getFlagUrl("SM")),
            Country("ST", "Sao Tome and Principe", "+239", Country.getFlagUrl("ST")),
            Country("SA", "Saudi Arabia", "+966", Country.getFlagUrl("SA")),
            Country("SN", "Senegal", "+221", Country.getFlagUrl("SN")),
            Country("RS", "Serbia", "+381", Country.getFlagUrl("RS")),
            Country("SC", "Seychelles", "+248", Country.getFlagUrl("SC")),
            Country("SL", "Sierra Leone", "+232", Country.getFlagUrl("SL")),
            Country("SG", "Singapore", "+65", Country.getFlagUrl("SG")),
            Country("SK", "Slovakia", "+421", Country.getFlagUrl("SK")),
            Country("SI", "Slovenia", "+386", Country.getFlagUrl("SI")),
            Country("SB", "Solomon Islands", "+677", Country.getFlagUrl("SB")),
            Country("SO", "Somalia", "+252", Country.getFlagUrl("SO")),
            Country("ZA", "South Africa", "+27", Country.getFlagUrl("ZA")),
            Country("KR", "South Korea", "+82", Country.getFlagUrl("KR")),
            Country("SS", "South Sudan", "+211", Country.getFlagUrl("SS")),
            Country("ES", "Spain", "+34", Country.getFlagUrl("ES")),
            Country("LK", "Sri Lanka", "+94", Country.getFlagUrl("LK")),
            Country("SD", "Sudan", "+249", Country.getFlagUrl("SD")),
            Country("SR", "Suriname", "+597", Country.getFlagUrl("SR")),
            Country("SE", "Sweden", "+46", Country.getFlagUrl("SE")),
            Country("CH", "Switzerland", "+41", Country.getFlagUrl("CH")),
            Country("SY", "Syria", "+963", Country.getFlagUrl("SY")),
            Country("TW", "Taiwan", "+886", Country.getFlagUrl("TW")),
            Country("TJ", "Tajikistan", "+992", Country.getFlagUrl("TJ")),
            Country("TZ", "Tanzania", "+255", Country.getFlagUrl("TZ")),
            Country("TH", "Thailand", "+66", Country.getFlagUrl("TH")),
            Country("TL", "Timor-Leste", "+670", Country.getFlagUrl("TL")),
            Country("TG", "Togo", "+228", Country.getFlagUrl("TG")),
            Country("TO", "Tonga", "+676", Country.getFlagUrl("TO")),
            Country("TT", "Trinidad and Tobago", "+1-868", Country.getFlagUrl("TT"), minLength = 10, maxLength = 10),
            Country("TN", "Tunisia", "+216", Country.getFlagUrl("TN")),
            Country("TR", "Turkey", "+90", Country.getFlagUrl("TR")),
            Country("TM", "Turkmenistan", "+993", Country.getFlagUrl("TM")),
            Country("TV", "Tuvalu", "+688", Country.getFlagUrl("TV")),
            Country("UG", "Uganda", "+256", Country.getFlagUrl("UG")),
            Country("UA", "Ukraine", "+380", Country.getFlagUrl("UA")),
            Country("AE", "United Arab Emirates", "+971", Country.getFlagUrl("AE")),
            Country("GB", "United Kingdom", "+44", Country.getFlagUrl("GB"), minLength = 10, maxLength = 10),
            Country("US", "United States", "+1", Country.getFlagUrl("US"), minLength = 10, maxLength = 10),
            Country("UY", "Uruguay", "+598", Country.getFlagUrl("UY")),
            Country("UZ", "Uzbekistan", "+998", Country.getFlagUrl("UZ")),
            Country("VU", "Vanuatu", "+678", Country.getFlagUrl("VU")),
            Country("VA", "Vatican City", "+379", Country.getFlagUrl("VA")),
            Country("VE", "Venezuela", "+58", Country.getFlagUrl("VE")),
            Country("VN", "Vietnam", "+84", Country.getFlagUrl("VN")),
            Country("YE", "Yemen", "+967", Country.getFlagUrl("YE")),
            Country("ZM", "Zambia", "+260", Country.getFlagUrl("ZM")),
            Country("ZW", "Zimbabwe", "+263", Country.getFlagUrl("ZW")),
        )
}
