name: PR Ad-hoc Build for Yral-Staging (Firebase)

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - ready_for_review
      - synchronize

jobs:
  build-ad-hoc-staging:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v2
        with:
          xcode-version: '16.2'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane + Firebase plugin
        run: |
          gem install fastlane
          fastlane add_plugin firebase_app_distribution

      - name: Decrypt and import Dev Certificate
        run: |
          mkdir -p certs
          echo "${{ secrets.YRAL_STAGING_DEV_CERT_P12_BASE64 }}" | base64 --decode > certs/Yral-Staging-Dev.p12
          echo "${{ secrets.YRAL_STAGING_DEV_PROF_BASE64 }}" | base64 --decode > certs/Yral-Staging-Dev.mobileprovision
          
          security create-keychain -p "" build.keychain
          security import certs/Yral-Staging-Dev.p12 -k ~/Library/Keychains/build.keychain -P ${{ secrets.IOS_CERTIFICATE_PASSWORD }} -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security set-keychain-settings -lut 21600s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain

      - name: Build & Distribute via Firebase
        run: fastlane ios build_staging_firebase
        env:
          FIREBASE_APP_ID_STAGING: ${{ secrets.FIREBASE_APP_ID_STAGING }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}