name: Publish Rust lib to github packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release'
        required: true
        default: '1.0'

permissions:
  contents: read
  packages: write

jobs:
  build-apk:
    runs-on: macos-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install android SDK
        uses: android-actions/setup-android@v3

      - name: Update version code
        run: |
          sed -i '' -E "s/version[[:space:]]*=[[:space:]]*\"[0-9]+\.[0-9]+\"/version = \"${{ github.event.inputs.version }}\"/" ./shared/rust/rust-agent/build.gradle.kts
          cat ./shared/rust/rust-agent/build.gradle.kts | grep version 

      - name: Clean project
        run: ./gradlew clean

      - name: Publish to Github packages
        run: ./gradlew shared:rust:rust-agent:publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: ${{ steps.setup-jdk.outputs.java-home }}
