name: Publish Rust lib to Maven local
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release'
        required: true
        default: '1.0'

#permissions:
#  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install android SDK
        uses: android-actions/setup-android@v3
        continue-on-error: true

      - name: Update version code
        run: |
          sed -i 's/version[[:space:]]*=[[:space:]]*[0-9][0-9]*/version = '"${{ github.event.inputs.version }}"'/' ./shared/rust/build.gradle.kts
          cat ./shared/rust/build.gradle.kts | grep version 

      - name: Clean project
        run: ./gradlew clean

      - name: Publish to maven local
        run: ./gradlew shared:rust:publishToMavenLocal
        env:
          JAVA_HOME: ${{ steps.setup-jdk.outputs.java-home }}
        continue-on-error: true

#      - name: Create Github Release (production-release)
#        id: create_release
#        uses: ncipollo/release-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: rustLib-${{ github.event.inputs.version }}
#          name: rustLib-${{ github.event.inputs.version }}
#          draft: false
#          prerelease: false
